### PR TITLE
Updated Hunter to 5.3.3

### PR DESCRIPTION
**Pull request by pasical**

### CODE REVIEW

**Comment by CanerKaraca23** [comment]
> _ No description provided. _

Can you share new latest? (I guess 5.5.0)

**Comment by pasical** [comment]
> > _ No description provided. _
> 
> Can you share new latest? (I guess 5.5.0)

It seems that I will not receive any updates. The latest version I can find is 5.3.8.

**Comment by pasical** [comment]
> Can you share new latest? (I guess 5.5.0)

Oh, I have found it. The latest one is 5.5.0, updated on March 12th. I will upload it soon.

**Comment by CanerKaraca23** [comment]
> > Can you share new latest? (I guess 5.5.0)
> 
> Oh, I have found it. The latest one is 5.5.0, updated on March 12th. I will upload it soon.

Can you share the source? I don't get the update pop-up on app.

Edit: I found.

**Comment by pasical** [comment]
> > > Can you share new latest? (I guess 5.5.0)
> > 
> > Oh, I have found it. The latest one is 5.5.0, updated on March 12th. I will upload it soon.
> 
> Can you share the source? I don't get the update pop-up on app.
> 
> Edit: I found.

It is a teaching app for a paid course on the Chinese platform "Knowledge Planet", which is not public. Maybe you can get the latest version only by contacting the author. I got the latest version from a web disk shared by a user on a Chinese forum Coolapk.

**Comment by CanerKaraca23** [comment]
> > > > Can you share new latest? (I guess 5.5.0)
> > > 
> > > 
> > > Oh, I have found it. The latest one is 5.5.0, updated on March 12th. I will upload it soon.
> > 
> > 
> > Can you share the source? I don't get the update pop-up on app.
> > Edit: I found.
> 
> It is a teaching app for a paid course on the Chinese platform "Knowledge Planet", which is not public. Maybe you can get the latest version only by contacting the author. I got the latest version from a web disk shared by a user on a Chinese forum Coolapk.

I understand, thanks.

**Pull request merged**
